const mapas = {
  "nivel-1": [
     {
      nome: "Nível 1",
      subnome: "60m² - 80m²",
      dificuldadeRaio: 520,
      dificuldadeTempo: 20,
      imagem: "../img/nivel-1/mapa-1.svg",
      roteadores: 1,
      tamanho: "600px",
      abrangencia: {
        width: "600px",
        height: "600px",
      },
      areas: [
        {
          nome: "banheiro",
          top: "1.9%",
          left: "1.9%",
          width: "17.9%",
          height: "43.7%",
        },
        {
          nome: "quarto",
          top: "1.9%",
          left: "22%",
          width: "43.8%",
          height: "43.7%",
        },
        {
          nome: "cozinha",
          top: "47.6%",
          left: "1.9%",
          width: "63.7%",
          height: "50.4%",
        },
        {
          nome: "sala",
          top: "62.9%",
          left: "65.6%",
          width: "32.35%",
          height: "35.1%",
        },
      ],
    }, 
    {
      nome: "Nível 1",
      subnome: "60m² - 80m²",
      dificuldadeRaio: 520,
      dificuldadeTempo: 20,
      imagem: "../img/nivel-1/mapa-2.svg",
      roteadores: 1,
      tamanho: "1000px",
      abrangencia: {
        width: "620px",
        height: "620px",
      },
      areas: [
        {
          nome: "quarto",
          top: "2.2%",
          left: "28.7%",
          width: "24.4%",
          height: "44.8%",
        },
        {
          nome: "banheiro",
          top: "49.3%",
          left: "41.5%",
          width: "11.5%",
          height: "48.4%",
        },
        {
          nome: "sala",
          top: "2.2%",
          left: "54.2%",
          width: "39%",
          height: "61.7%",
        },
        {
          nome: "sala-recorte",
          top: "32%",
          left: "93.2%",
          width: "5.35%",
          height: "32%",
        },
        {
          nome: "sala-angulo",
          top: "22.3%",
          left: "93.2%",
          width: "5.5%",
          height: "9.8%",
          clipPath: "polygon(0% 0%, 0% 100%, 100% 100%)",
        },
        {
          nome: "cozinha",
          top: "66%",
          left: "54.2%",
          width: "44.35%",
          height: "31.6%",
        },


      ],
    },
  ],
  "nivel-2": [
     {
      nome: "Nível 2",
      subnome: "80m² - 100m²",
      dificuldadeRaio: 390,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-2/mapa-1.svg",
      roteadores: 2,
      tamanho: "900px",
      abrangencia: {
        width: "450px",
        height: "450px",
      },
      areas: [
        {
          nome: "sala",
          top: "2.2%",
          left: "61.4%",
          width: "32.85%",
          height: "62%",
        },
        {
          nome: "sala-angulo",
          top: "22%",
          left: "94.21%",
          width: "4.7%",
          height: "10%",
          clipPath: "polygon(0% 0%, 0% 100%, 100% 100%)",
        },
        {
          nome: "sala-recorte",
          top: "32%",
          left: "94.21%",
          width: "4.53%",
          height: "32.2%",
        },
        {
          nome: "corredor",
          top: "49.3%",
          left: "20.7%",
          width: "40.7%",
          height: "14.9%",
        },
        {
          nome: "cozinha",
          top: "66.1%",
          left: "61.4%",
          width: "37.35%",
          height: "31.8%",
        },
        {
          nome: "quarto_1",
          top: "2.2%",
          left: "1.1%",
          width: "27.2%",
          height: "44.9%",
        },
        {
          nome: "quarto_2",
          top: "2.2%",
          left: "40%",
          width: "20.4%",
          height: "44.9%",
        },
        {
          nome: "quarto_3",
          top: "49.3%",
          left: "1.1%",
          width: "18.6%",
          height: "48.6%",
        },
        {
          nome: "quarto_3-recorte",
          top: "66.1%",
          left: "19.7%",
          width: "24.2%",
          height: "31.8%",
        },
        {
          nome: "banheiro_1",
          top: "2.2%",
          left: "29.3%",
          width: "9.7%",
          height: "44.7%",
        },
        {
          nome: "banheiro_2",
          top: "66.1%",
          left: "44.9%",
          width: "15.5%",
          height: "31.8%",
        },
      ],
    },  
     {
      nome: "Nível 2",
      subnome: "80m² - 100m²",
      dificuldadeRaio: 360,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-2/mapa-2.svg",
      roteadores: 2,
      tamanho: "950px",
      abrangencia: {
        width: "400px",
        height: "400px",
      },
      areas: [
        {
          nome: "banheiro_1",
          top: "2.5%",
          left: "1.1%",
          width: "20.8%",
          height: "26.4%",
        },
        {
          nome: "quarto_1",
          top: "31.4%",
          left: "1.1%",
          width: "20.8%",
          height: "66%",
        },
        {
          nome: "quarto_1-recorte",
          top: "78%",
          left: "21.9%",
          width: "6%",
          height: "19.5%",
        },
        {
          nome: "dormitorio",
          top: "2.5%",
          left: "22.8%",
          width: "22.8%",
          height: "33.9%",
        },
        {
          nome: "dormitorio-recorte",
          top: "36.4%",
          left: "22.8%",
          width: "18.4%",
          height: "39.4%",
        },
        {
          nome: "lavanderia",
          top: "2.5%",
          left: "46.5%",
          width: "11%",
          height: "34%",
        },
        {
          nome: "banheiro_2",
          top: "38.7%",
          left: "42.3%",
          width: "15.3%",
          height: "37.2%",
        },
        {
          nome: "corredor",
          top: "78.5%",
          left: "28.9%",
          width: "29.68%",
          height: "19%",
        },
        {
          nome: "cozinha",
          top: "2.5%",
          left: "58.6%",
          width: "20.7%",
          height: "39.7%",
        },
        {
          nome: "sala",
          top: "42.2%",
          left: "58.6%",
          width: "40.3%",
          height: "55.3%",
        },
      ],
    },
    
    {
      nome: "Nível 2",
      subnome: "80m² - 100m²",
      dificuldadeRaio: 380,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-2/mapa-3.svg",
      roteadores: 2,
      tamanho: "900px",
      abrangencia: {
        width: "470px",
        height: "470px",
      },
      areas: [
        {
          nome: "lavanderia",
          top: "2.2%",
          left: "1.1%",
          width: "10.9%",
          height: "44.2%",
        },
        {
          nome: "banheiro",
          top: "2.2%",
          left: "13%",
          width: "18.2%",
          height: "26.5%",
        },
        {
          nome: "quarto",
          top: "2.2%",
          left: "32.2%",
          width: "23.87%",
          height: "43.8%",
        },
        {
          nome: "dormitorio",
          top: "48.2%",
          left: "1.1%",
          width: "17%",
          height: "49.7%",
        },
        {
          nome: "dormitorio-recorte",
          top: "58%",
          left: "18.1%",
          width: "5.2%",
          height: "39.8%",
        },
        {
          nome: "dormitorio-angulo",
          top: "48.5%",
          left: "18.1%",
          width: "5.2%",
          height: "9.6%",
          clipPath: "polygon(0% 0%, 0% 100%, 100% 100%)",
        },
        {
          nome: "corredor",
          top: "30.5%",
          left: "13%",
          width: "18.1%",
          height: "16%",
        },
        {
          nome: "cozinha-recorte",
          top: "46.4%",
          left: "24.2%",
          width: "6.9%",
          height: "1.4%",
        },
        {
          nome: "cozinha-angulo",
          top: "46.4%",
          left: "18.02%",
          width: "6.2%",
          height: "11%",
          clipPath: "polygon(0% 0%, 100% 0%, 100% 100%)",
        },
        {
          nome: "cozinha",
          top: "47.8%",
          left: "24.27%",
          width: "34.7%",
          height: "50%",
        },
        {
          nome: "sala",
          top: "62.8%",
          left: "59%",
          width: "17.7%",
          height: "35%",
        },
        
      ],
    },
    
    
    {
      nome: "Nível 2",
      subnome: "80m² - 100m²",
      dificuldadeRaio: 375,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-2/mapa-4.svg",
      roteadores: 2,
      tamanho: "1200px",
      abrangencia: {
        width: "450px",
        height: "450px",
      },
      areas: [
        {
          nome: "quarto",
          top: "2.1%",
          left: "0.8%",
          width: "16.8%",
          height: "50%",
        },
        {
          nome: "quarto-recorte",
          top: "39%",
          left: "17.6%",
          width: "9.2%",
          height: "13.1%",
        },
        {
          nome: "banheiro_1",
          top: "2.1%",
          left: "18.4%",
          width: "8.5%",
          height: "35%",
        },
        {
          nome: "banheiro_2",
          top: "2.1%",
          left: "27.6%",
          width: "8.5%",
          height: "35%",
        },
        {
          nome: "dormitorio_1",
          top: "2.1%",
          left: "36.9%",
          width: "15.7%",
          height: "35%",
        },
        {
          nome: "dormitorio_2",
          top: "2.1%",
          left: "53.4%",
          width: "13.5%",
          height: "50%",
        },
        {
          nome: "dormitorio_2-recorte",
          top: "39%",
          left: "47.5%",
          width: "5.9%",
          height: "13.2%",
        },
        {
          nome: "corredor",
          top: "39%",
          left: "27.7%",
          width: "19%",
          height: "13.2%",
        },
        {
          nome: "lavanderia",
          top: "54%",
          left: "0.8%",
          width: "5.5%",
          height: "44.1%",
        },
        {
          nome: "cozinha",
          top: "54%",
          left: "7.2%",
          width: "22%",
          height: "44.1%",
        },
        {
          nome: "sala",
          top: "54%",
          left: "29.2%",
          width: "28.9%",
          height: "44.1%",
        },
      ],
    }, 
  ],
  "nivel-3": [

/*     {
      nome: "Nível 3",
      subnome: "100m² - 120m²",
      dificuldadeRaio: 410,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-3/mapa-1.svg",
      roteadores: 2,
      tamanho: "1100px",
      abrangencia: {
        width: "490px",
        height: "490px",
      },
      areas: [
        {
          nome: "sala",
          top: "55.8%",
          left: "61.3%",
          width: "30.3%",
          height: "42.4%",
        },
        {
          nome: "sala-recorte",
          top: "67.2%",
          left: "91.6%",
          width: "7.4%",
          height: "31%",
        },
        {
          nome: "corredor",
          top: "42.3%",
          left: "14.8%",
          width: "46.1%",
          height: "11.9%",
        },
        {
          nome: "cozinha_1",
          top: "55.8%",
          left: "37.3%",
          width: "24%",
          height: "42.4%",
        },
        {
          nome: "cozinha_1-2",
          top: "55.8%",
          left: "14.8%",
          width: "22.5%",
          height: "42.4%",
        },
        {
          nome: "quarto_1",
          top: "1.7%",
          left: "0.87%",
          width: "20.1%",
          height: "31.2%",
        },
        {
          nome: "quarto_1-recorte",
          top: "32.9%",
          left: "14.8%",
          width: "6.2%",
          height: "7.6%",
        },
        {
          nome: "quarto_2",
          top: "1.7%",
          left: "30.7%",
          width: "17.1%",
          height: "38.8%",
        },
        {
          nome: "quarto_3",
          top: "1.7%",
          left: "48.7%",
          width: "12.3%",
          height: "38.8%",
        },
        {
          nome: "quarto_4",
          top: "1.7%",
          left: "61.8%",
          width: "17.2%",
          height: "52.3%",
        },
        {
          nome: "quarto_4-recorte",
          top: "35.4%",
          left: "79%",
          width: "12.7%",
          height: "18.6%",
        },
        {
          nome: "banheiro_1",
          top: "1.7%",
          left: "21.8%",
          width: "8%",
          height: "38.8%",
        },
        {
          nome: "banheiro_2",
          top: "1.7%",
          left: "79.8%",
          width: "11.9%",
          height: "32%",
        },
        {
          nome: "lavanderia",
          top: "34.8%",
          left: "0.87%",
          width: "13.1%",
          height: "19.2%",
        },
      ],
    }, */
 /*        {
      nome: "Nível 3",
      subnome: "100m² - 120m²",
      dificuldadeRaio: 485,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-3/mapa-2.svg",
      roteadores: 2,
      tamanho: "950px",
      abrangencia: {
        width: "590px",
        height: "590px",
      },
      areas: [
        {
          nome: "quarto_1",
          top: "1.5%",
          left: "1%",
          width: "12%",
          height: "19.8%",
        },
        {
          nome: "quarto_1-1",
          top: "21.3%",
          left: "1%",
          width: "30.5%",
          height: "10.8%",
        },
         {
          nome: "quarto_1-2",
          top: "32.1%",
          left: "5.4%",
          width: "26.1%",
          height: "23.2%",
        },
        {
          nome: "quarto_1-3",
          top: "43%",
          left: "31.5%",
          width: "8%",
          height: "12.3%",
        }, 
        {
          nome: "banheiro_1",
          top: "1.5%",
          left: "14%",
          width: "17.5%",
          height: "18.25%",
        }, 
        {
          nome: "area_luz",
          top: "1.5%",
          left: "32.5%",
          width: "17.6%",
          height: "22%",
        }, 
        {
          nome: "banheiro_2",
          top: "25%",
          left: "32.5%",
          width: "17.6%",
          height: "16.3%",
        }, 
        {
          nome: "quarto_2",
          top: "1.5%",
          left: "51%",
          width: "19.8%",
          height: "40%",
        },
        {
          nome: "quarto_3",
          top: "1.5%",
          left: "71.7%",
          width: "12%",
          height: "22.3%",
        },
        {
          nome: "quarto_3-recorte",
          top: "23.8%",
          left: "71.7%",
          width: "27.3%",
          height: "31.3%",
        },
        {
          nome: "banheiro_3",
          top: "1.5%",
          left: "84.8%",
          width: "14.3%",
          height: "20.8%",
        },
        {
          nome: "corredor",
          top: "42.8%",
          left: "40.4%",
          width: "30.3%",
          height: "12.3%",
        },
        {
          nome: "lavanderia",
          top: "56.8%",
          left: "1%",
          width: "10.3%",
          height: "21.1%",
        },
        {
          nome: "lavabo",
          top: "79.4%",
          left: "1%",
          width: "10.3%",
          height: "18.7%",
        },
        {
          nome: "cozinha",
          top: "56.8%",
          left: "12.3%",
          width: "35.5%",
          height: "41.3%",
        },
        {
          nome: "sala",
          top: "56.8%",
          left: "47.8%",
          width: "39.5%",
          height: "41.3%",
        },
      ],
    },  */
/*     {
      nome: "Nível 3",
      subnome: "100m² - 120m²",
      dificuldadeRaio: 400,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-3/mapa-3.svg",
      roteadores: 2,
      tamanho: "1050px",
      abrangencia: {
        width: "440px",
        height: "440px",
      },
      areas: [
        {
          nome: "cozinha",
          top: "16%",
          left: "0.9%",
          width: "12.7%",
          height: "32%",
        },
         {
          nome: "cozinha-recorte",
          top: "16%",
          left: "13.6%",
          width: "7%",
          height: "39.8%",
        }, 
          {
            nome: "sala",
            top: "16%",
            left: "26.95%",
            width: "10.9%",
            height: "33.6%",
          },
          {
            nome: "sala-recorte",
            top: "16%",
            left: "20.6%",
            width: "6.4%",
            height: "36.8%",
          },
          {
            nome: "sala-corredor_1",
            top: "16%",
            left: "37.8%",
            width: "6%",
            height: "38.6%",
          },
          {
            nome: "sala-corredor_2",
            top: "16%",
            left: "48.98%",
            width: "2.9%",
            height: "38.6%",
          },
          {
            nome: "sala-corredor_recorte",
            top: "16%",
            left: "43.8%",
            width: "5.2%",
            height: "50.2%",
          },
          {
            nome: "lavanderia",
            top: "49.4%",
            left: "0.9%",
            width: "12%",
            height: "16.8%",
          },
          {
            nome: "corredor",
            top: "57%",
            left: "13.6%",
            width: "13.4%",
            height: "9.2%",
          },
          {
            nome: "corredor-recorte",
            top: "54.2%",
            left: "21.3%",
            width: "5.7%",
            height: "2.8%",
          },
          {
            nome: "banheiro_1",
            top: "51%",
            left: "27.7%",
            width: "9.3%",
            height: "15.2%",
          },
          {
            nome: "banheiro_1-recorte",
            top: "56%",
            left: "36.95%",
            width: "6.2%",
            height: "10.2%",
          },
          {
            nome: "quarto_1",
            top: "67.5%",
            left: "0.9%",
            width: "18.2%",
            height: "31%",
          },
          {
            nome: "quarto_2",
            top: "67.5%",
            left: "19.8%",
            width: "17.1%",
            height: "31%",
          },
          {
            nome: "area_livre",
            top: "67.5%",
            left: "37.6%",
            width: "11.4%",
            height: "31%",
          },          
          {
            nome: "banheiro_2",
            top: "67.5%",
            left: "49.6%",
            width: "8.2%",
            height: "31%",
          },
          {
            nome: "quarto_3",
            top: "66.2%",
            left: "58.6%",
            width: "18.3%",
            height: "32.3%",
          },
          {
            nome: "quarto_3-recorte",
            top: "56%",
            left: "49.7%",
            width: "27.2%",
            height: "10.2%",
          },
      ],
    }, */
         {
      nome: "Nível 3",
      subnome: "100m² - 120m²",
      dificuldadeRaio: 400,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-3/mapa-4.svg",
      roteadores: 2,
      tamanho: "900px",
      abrangencia: {
        width: "440px",
        height: "440px",
      },
      areas: [
        {
          nome: "cozinha",
          top: "16%",
          left: "0.9%",
          width: "12.7%",
          height: "32%",
        },
      ],
    }, 
  ],
  "nivel-4": [
    {
      nome: "Nível 4",
      subnome: "120m² - 170m²",
      dificuldadeRaio: 440,
      dificuldadeTempo: 30,
      imagem: "../img/nivel-4/mapa-1.svg",
      roteadores: 3,
      tamanho: "800px",
      abrangencia: {
        width: "100px",
        height: "100px",
      },
      areas: [
        {
          nome: "festeiro",
          top: "1.4%",
          left: "0.85%",
          width: "26.95%",
          height: "38.1%",
        },
      ],

    },
/*     {
      nome: "Nível 4",
      subnome: "120m² - 170m²",
      dificuldadeRaio: 440,
      dificuldadeTempo: 30,
      imagem: "../img/nivel-4/mapa-2.svg",
      roteadores: 3,
      tamanho: "800px",
      abrangencia: {
        width: "100px",
        height: "100px",
      },
      areas: [
        {
          nome: "festeiro",
          top: "1.4%",
          left: "0.85%",
          width: "26.95%",
          height: "38.1%",
        },
      ],

    },
    {
      nome: "Nível 4",
      subnome: "120m² - 170m²",
      dificuldadeRaio: 440,
      dificuldadeTempo: 30,
      imagem: "../img/nivel-4/mapa-3.svg",
      roteadores: 3,
      tamanho: "800px",
      abrangencia: {
        width: "100px",
        height: "100px",
      },
      areas: [
        {
          nome: "festeiro",
          top: "1.4%",
          left: "0.85%",
          width: "26.95%",
          height: "38.1%",
        },
      ],

    },
    {
      nome: "Nível 4",
      subnome: "120m² - 170m²",
      dificuldadeRaio: 440,
      dificuldadeTempo: 30,
      imagem: "../img/nivel-4/mapa-4.svg",
      roteadores: 3,
      tamanho: "800px",
      abrangencia: {
        width: "100px",
        height: "100px",
      },
      areas: [
        {
          nome: "festeiro",
          top: "1.4%",
          left: "0.85%",
          width: "26.95%",
          height: "38.1%",
        },
      ],

    }, */
  ],

  "nivel-5": [
    {
      nome: "Nível 5",
      subnome: "170m²+",
      dificuldadeRaio: 440,
      dificuldadeTempo: 30,
      imagem: "../img/nivel-5/mapa-1.svg",
      roteadores: 5,
      tamanho: "800px",
      abrangencia: {
        width: "100px",
        height: "100px",
      },
      areas: [
        {
          nome: "festeiro",
          top: "1.4%",
          left: "0.85%",
          width: "26.95%",
          height: "38.1%",
        },
  ],
},
{
  nome: "Nível 5",
  subnome: "170m²+",
  dificuldadeRaio: 440,
  dificuldadeTempo: 30,
  imagem: "../img/nivel-5/mapa-2.svg",
  roteadores: 5,
  tamanho: "800px",
  abrangencia: {
    width: "100px",
    height: "100px",
  },
  areas: [
    {
      nome: "festeiro",
      top: "1.4%",
      left: "0.85%",
      width: "26.95%",
      height: "38.1%",
    },
],
},
{
  nome: "Nível 5",
  subnome: "170m²+",
  dificuldadeRaio: 440,
  dificuldadeTempo: 30,
  imagem: "../img/nivel-5/mapa-3.svg",
  roteadores: 5,
  tamanho: "800px",
  abrangencia: {
    width: "100px",
    height: "100px",
  },
  areas: [
    {
      nome: "festeiro",
      top: "1.4%",
      left: "0.85%",
      width: "26.95%",
      height: "38.1%",
    },
],
},
],
};

export { mapas };
