const mapas = {
  "nivel-1": [
    
  {
      nome: "Nível 1",
      subnome: "60m² - 80m²",
      dificuldadeRaio: 400,
      dificuldadeTempo: 20,
      imagem: "../img/nivel-1/mapa-1.svg",
      roteadores: 1,
      tamanho: "400px",
      abrangencia: {
        width: "470px",
        height: "470px",
      },
      areas: [
        {
          nome: "banheiro",
          top: "1.9%",
          left: "1.9%",
          width: "17.9%",
          height: "43.7%",
        },
        {
          nome: "quarto",
          top: "1.9%",
          left: "22%",
          width: "43.8%",
          height: "43.7%",
        },
        {
          nome: "cozinha",
          top: "47.6%",
          left: "1.9%",
          width: "63.7%",
          height: "50.4%",
        },
        {
          nome: "sala",
          top: "62.9%",
          left: "65.6%",
          width: "32.35%",
          height: "35.1%",
        },
      ],
    }, 
    {
      nome: "Nível 1",
      subnome: "60m² - 80m²",
      dificuldadeRaio: 430,
      dificuldadeTempo: 20,
      imagem: "../img/nivel-1/mapa-2.svg",
      roteadores: 1,
      tamanho: "700px",
      abrangencia: {
        width: "452px",
        height: "420px",
      },
      areas: [
        {
          nome: "quarto",
          top: "2.2%",
          left: "28.7%",
          width: "24.4%",
          height: "44.8%",
        },
        {
          nome: "banheiro",
          top: "49.3%",
          left: "41.5%",
          width: "11.5%",
          height: "48.4%",
        },
        {
          nome: "sala",
          top: "2.2%",
          left: "54.2%",
          width: "20%",
          height: "61.7%",
        },
        {
          nome: "sala-dois",
          top: "2.2%",
          left: "74.2%",
          width: "19%",
          height: "61.7%",
        },
        {
          nome: "sala-recorte",
          top: "32%",
          left: "93.2%",
          width: "5.35%",
          height: "32%",
        },
        {
          nome: "sala-angulo",
          top: "22.3%",
          left: "93.2%",
          width: "5.5%",
          height: "9.8%",
          clipPath: "polygon(0% 0%, 0% 100%, 100% 100%)",
        },
        {
          nome: "cozinha",
          top: "66%",
          left: "54.2%",
          width: "44.35%",
          height: "31.6%",
        },
      ],
    },
   
      {
      nome: "Nível 1",
      subnome: "60m² - 80m²",
      dificuldadeRaio: 350,
      dificuldadeTempo: 20,
      imagem: "../img/nivel-1/mapa-3.svg",
      roteadores: 1,
      tamanho: "900px",
      abrangencia: {
        width: "360px",
        height: "360px",
      },
      areas: [
        {
          nome: "sala",
          top: "33.7%",
          left: "22.3%",
          width: "17.2%",
          height: "46.5%",
        },
        {
          nome: "sala-recorte",
          top: "33.7%",
          left: "39.45%",
          width: "12.4%",
          height: "24%",
        },
        {
          nome: "banheiro",
          top: "33.7%",
          left: "52.6%",
          width: "8.1%",
          height: "24%",
        },
        {
          nome: "quarto",
          top: "58.8%",
          left: "40.3%",
          width: "20.5%",
          height: "21.4%",
        },
      ],
    },
    
    
    {
      nome: "Nível 1",
      subnome: "60m² - 80m²",
      dificuldadeRaio: 370,
      dificuldadeTempo: 20,
      imagem: "../img/nivel-1/mapa-4.svg",
      roteadores: 1,
      tamanho: "800px",
      abrangencia: {
        width: "430px",
        height: "430px",
      },
      areas: [
        {
          nome: "sala",
          top: "1.4%",
          left: "24.8%",
          width: "22.6%",
          height: "63.4%",
        },
        {
          nome: "banheiro",
          top: "1.4%",
          left: "48.4%",
          width: "9%",
          height: "31.1%",
        },
        {
          nome: "quarto",
          top: "33.8%",
          left: "48.4%",
          width: "13.7%",
          height: "31.1%",
        },
      ],
    },   
  ],
  "nivel-2": [
       {
      nome: "Nível 2",
      subnome: "80m² - 100m²",
      dificuldadeRaio: 430,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-2/mapa-1.svg",
      roteadores: 2,
      tamanho: "800px",
      abrangencia: {
        width: "380px",
        height: "380px",
      },
      areas: [
        {
          nome: "sala",
          top: "2.2%",
          left: "61.4%",
          width: "32.85%",
          height: "62%",
        },
        {
          nome: "sala-angulo",
          top: "22%",
          left: "94.21%",
          width: "4.7%",
          height: "10%",
          clipPath: "polygon(0% 0%, 0% 100%, 100% 100%)",
        },
        {
          nome: "sala-recorte",
          top: "32%",
          left: "94.21%",
          width: "4.53%",
          height: "32.2%",
        },
        {
          nome: "corredor",
          top: "49.3%",
          left: "20.7%",
          width: "40.7%",
          height: "14.9%",
        },
        {
          nome: "cozinha",
          top: "66.1%",
          left: "61.4%",
          width: "37.35%",
          height: "31.8%",
        },
        {
          nome: "quarto_1",
          top: "2.2%",
          left: "1.1%",
          width: "27.2%",
          height: "44.9%",
        },
        {
          nome: "quarto_2",
          top: "2.2%",
          left: "40%",
          width: "20.4%",
          height: "44.9%",
        },
        {
          nome: "quarto_3",
          top: "49.3%",
          left: "1.1%",
          width: "18.6%",
          height: "48.6%",
        },
        {
          nome: "quarto_3-recorte",
          top: "66.1%",
          left: "19.7%",
          width: "24.2%",
          height: "31.8%",
        },
        {
          nome: "banheiro_1",
          top: "2.2%",
          left: "29.3%",
          width: "9.7%",
          height: "44.7%",
        },
        {
          nome: "banheiro_2",
          top: "66.1%",
          left: "44.9%",
          width: "15.5%",
          height: "31.8%",
        },
      ],
    },  
    
    {
      nome: "Nível 2",
      subnome: "80m² - 100m²",
      dificuldadeRaio: 390,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-2/mapa-2.svg",
      roteadores: 2,
      tamanho: "900px",
      abrangencia: {
        width: "390px",
        height: "390px",
      },
      areas: [
        {
          nome: "banheiro_1",
          top: "2.5%",
          left: "1.1%",
          width: "20.8%",
          height: "26.4%",
        },
        {
          nome: "quarto_1",
          top: "31.4%",
          left: "1.1%",
          width: "20.8%",
          height: "66%",
        },
        {
          nome: "quarto_1-recorte",
          top: "78%",
          left: "21.9%",
          width: "6%",
          height: "19.5%",
        },
        {
          nome: "dormitorio",
          top: "2.5%",
          left: "22.8%",
          width: "22.8%",
          height: "33.9%",
        },
        {
          nome: "dormitorio-recorte",
          top: "36.4%",
          left: "22.8%",
          width: "18.4%",
          height: "39.4%",
        },
        {
          nome: "lavanderia",
          top: "2.5%",
          left: "46.5%",
          width: "11%",
          height: "34%",
        },
        {
          nome: "banheiro_2",
          top: "38.7%",
          left: "42.3%",
          width: "15.3%",
          height: "37.2%",
        },
        {
          nome: "corredor",
          top: "78.5%",
          left: "28.9%",
          width: "29.68%",
          height: "19%",
        },
        {
          nome: "cozinha",
          top: "2.5%",
          left: "58.6%",
          width: "20.7%",
          height: "39.7%",
        },
        {
          nome: "sala",
          top: "42.2%",
          left: "79.3%",
          width: "19.7%",
          height: "55.3%",
        },
        {
          nome: "sala-jantar",
          top: "42.2%",
          left: "58.6%",
          width: "20.7%",
          height: "55.3%",
        },
      ],
    }, 

     {
      nome: "Nível 2",
      subnome: "80m² - 100m²",
      dificuldadeRaio: 380,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-2/mapa-3.svg",
      roteadores: 2,
      tamanho: "800px",
      abrangencia: {
        width: "380px",
        height: "380px",
      },
      areas: [
        {
          nome: "lavanderia",
          top: "2.2%",
          left: "1.1%",
          width: "10.9%",
          height: "44.2%",
        },
        {
          nome: "banheiro",
          top: "2.2%",
          left: "13%",
          width: "18.2%",
          height: "26.5%",
        },
        {
          nome: "quarto",
          top: "2.2%",
          left: "32.2%",
          width: "23.87%",
          height: "43.8%",
        },
        {
          nome: "dormitorio",
          top: "48.2%",
          left: "1.1%",
          width: "17%",
          height: "49.7%",
        },
        {
          nome: "dormitorio-recorte",
          top: "58%",
          left: "18.1%",
          width: "5.2%",
          height: "39.8%",
        },
        {
          nome: "dormitorio-angulo",
          top: "48.5%",
          left: "18.05%",
          width: "5.2%",
          height: "9.6%",
          clipPath: "polygon(0% 0%, 0% 100%, 100% 100%)",
        },
        {
          nome: "corredor",
          top: "30.5%",
          left: "13%",
          width: "18.1%",
          height: "16%",
        },
        {
          nome: "cozinha-recorte",
          top: "46.5%",
          left: "24.25%",
          width: "6.9%",
          height: "1.4%",
        },
        {
          nome: "cozinha-angulo",
          top: "46.5%",
          left: "18.05%",
          width: "6.2%",
          height: "11%",
          clipPath: "polygon(0% 0%, 100% 0%, 100% 100%)",
        },
        {
          nome: "cozinha",
          top: "47.8%",
          left: "24.27%",
          width: "34.7%",
          height: "50%",
        },
        {
          nome: "sala",
          top: "62.8%",
          left: "59%",
          width: "17.7%",
          height: "35%",
        },
      ],
    },

    {
      nome: "Nível 2",
      subnome: "80m² - 100m²",
      dificuldadeRaio: 380,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-2/mapa-4.svg",
      roteadores: 2,
      tamanho: "1000px",
      abrangencia: {
        width: "400px",
        height: "400px",
      },
      areas: [
        {
          nome: "quarto",
          top: "2.1%",
          left: "0.8%",
          width: "16.8%",
          height: "50%",
        },
        {
          nome: "quarto-recorte",
          top: "39%",
          left: "17.6%",
          width: "9.2%",
          height: "13.1%",
        },
        {
          nome: "banheiro_1",
          top: "2.1%",
          left: "18.4%",
          width: "8.5%",
          height: "35%",
        },
        {
          nome: "banheiro_2",
          top: "2.1%",
          left: "27.6%",
          width: "8.5%",
          height: "35%",
        },
        {
          nome: "dormitorio_1",
          top: "2.1%",
          left: "36.9%",
          width: "15.7%",
          height: "35%",
        },
        {
          nome: "dormitorio_2",
          top: "2.1%",
          left: "53.4%",
          width: "13.5%",
          height: "50%",
        },
        {
          nome: "dormitorio_2-recorte",
          top: "39%",
          left: "47.5%",
          width: "5.9%",
          height: "13.2%",
        },
        {
          nome: "corredor",
          top: "39%",
          left: "27.7%",
          width: "19%",
          height: "13.2%",
        },
        {
          nome: "lavanderia",
          top: "54%",
          left: "0.8%",
          width: "5.5%",
          height: "44.1%",
        },
        {
          nome: "cozinha",
          top: "54%",
          left: "7.2%",
          width: "22%",
          height: "44.1%",
        },
        {
          nome: "sala",
          top: "54%",
          left: "29.2%",
          width: "28.9%",
          height: "44.1%",
        },
      ],
    },  
    
  ],
  "nivel-3": [
    
    {
      nome: "Nível 3",
      subnome: "100m² - 120m²",
      dificuldadeRaio: 350,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-3/mapa-1.svg",
      roteadores: 2,
      tamanho: "800px",
      abrangencia: {
        width: "350px",
        height: "350px",
      },
      areas: [
        {
          nome: "sala",
          top: "55.8%",
          left: "71.5%",
          width: "20.1%",
          height: "11.5%",
        },
        {
          nome: "sala-recorte",
          top: "67.2%",
          left: "71.5%",
          width: "27.5%",
          height: "31%",
        },
        {
          nome: "corredor",
          top: "42.3%",
          left: "14.8%",
          width: "46.1%",
          height: "11.9%",
        },
        {
          nome: "cozinha_1",
          top: "55.8%",
          left: "37.3%",
          width: "34.2%",
          height: "42.4%",
        },
        {
          nome: "cozinha_1_2",
          top: "55.8%",
          left: "14.8%",
          width: "22.5%",
          height: "42.4%",
        },
        {
          nome: "quarto_1",
          top: "1.7%",
          left: "0.87%",
          width: "20.1%",
          height: "31.2%",
        },
        {
          nome: "quarto_1-recorte",
          top: "32.9%",
          left: "14.8%",
          width: "6.2%",
          height: "7.6%",
        },
        {
          nome: "quarto_2",
          top: "1.7%",
          left: "30.7%",
          width: "17.1%",
          height: "38.8%",
        },
        {
          nome: "quarto_3",
          top: "1.7%",
          left: "48.7%",
          width: "12.3%",
          height: "38.8%",
        },
        {
          nome: "quarto_4",
          top: "1.7%",
          left: "61.8%",
          width: "17.2%",
          height: "52.3%",
        },
        {
          nome: "quarto_4-recorte",
          top: "35.4%",
          left: "79%",
          width: "12.7%",
          height: "18.6%",
        },
        {
          nome: "banheiro_1",
          top: "1.7%",
          left: "21.8%",
          width: "8%",
          height: "38.8%",
        },
        {
          nome: "banheiro_2",
          top: "1.7%",
          left: "79.8%",
          width: "11.9%",
          height: "32%",
        },
        {
          nome: "lavanderia",
          top: "34.8%",
          left: "0.87%",
          width: "13.1%",
          height: "19.2%",
        },
      ],
    },
      {
      nome: "Nível 3",
      subnome: "100m² - 120m²",
      dificuldadeRaio: 420,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-3/mapa-2.svg",
      roteadores: 2,
      tamanho: "750px",
      abrangencia: {
        width: "420px",
        height: "420px",
      },
      areas: [
        {
          nome: "quarto_1",
          top: "1.5%",
          left: "1%",
          width: "12%",
          height: "19.8%",
        },
        {
          nome: "quarto_1-1",
          top: "21.3%",
          left: "1%",
          width: "30.5%",
          height: "10.8%",
        },
        {
          nome: "quarto_1-2",
          top: "32.1%",
          left: "5.4%",
          width: "26.1%",
          height: "23.2%",
        },
        {
          nome: "quarto_1-3",
          top: "43%",
          left: "31.5%",
          width: "8%",
          height: "12.3%",
        },
        {
          nome: "banheiro_1",
          top: "1.5%",
          left: "14%",
          width: "17.5%",
          height: "18.25%",
        },
        {
          nome: "area_luz",
          top: "1.5%",
          left: "32.5%",
          width: "17.6%",
          height: "22%",
        },
        {
          nome: "banheiro_2",
          top: "25%",
          left: "32.5%",
          width: "17.6%",
          height: "16.3%",
        },
        {
          nome: "quarto_2",
          top: "1.5%",
          left: "51%",
          width: "19.8%",
          height: "40%",
        },
        {
          nome: "quarto_3",
          top: "1.5%",
          left: "71.7%",
          width: "12%",
          height: "22.3%",
        },
        {
          nome: "quarto_3-recorte",
          top: "23.8%",
          left: "71.7%",
          width: "27.3%",
          height: "31.3%",
        },
        {
          nome: "banheiro_3",
          top: "1.5%",
          left: "84.8%",
          width: "14.3%",
          height: "20.8%",
        },
        {
          nome: "corredor",
          top: "42.8%",
          left: "40.4%",
          width: "30.3%",
          height: "12.3%",
        },
        {
          nome: "lavanderia",
          top: "56.8%",
          left: "1%",
          width: "10.3%",
          height: "21.1%",
        },
        {
          nome: "lavabo",
          top: "79.4%",
          left: "1%",
          width: "10.3%",
          height: "18.7%",
        },
        {
          nome: "cozinha",
          top: "56.8%",
          left: "12.3%",
          width: "35.5%",
          height: "41.3%",
        },
        {
          nome: "sala",
          top: "56.8%",
          left: "47.8%",
          width: "39.5%",
          height: "41.3%",
        },
      ],
    },
    
    {
      nome: "Nível 3",
      subnome: "100m² - 120m²",
      dificuldadeRaio: 345,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-3/mapa-3.svg",
      roteadores: 2,
      tamanho: "900px",
      abrangencia: {
        width: "360px",
        height: "360px",
      },
      areas: [
        {
          nome: "cozinha",
          top: "16%",
          left: "0.9%",
          width: "12.7%",
          height: "32%",
        },
        {
          nome: "cozinha-recorte",
          top: "16%",
          left: "13.6%",
          width: "7%",
          height: "39.8%",
        },
        {
          nome: "sala",
          top: "16%",
          left: "26.95%",
          width: "10.9%",
          height: "33.6%",
        },
        {
          nome: "sala-recorte",
          top: "16%",
          left: "20.6%",
          width: "6.4%",
          height: "36.8%",
        },
        {
          nome: "sala-corredor_1",
          top: "16%",
          left: "37.8%",
          width: "6%",
          height: "38.6%",
        },
        {
          nome: "sala-corredor_2",
          top: "16%",
          left: "48.98%",
          width: "2.9%",
          height: "38.6%",
        },
        {
          nome: "sala-corredor_recorte",
          top: "16%",
          left: "43.8%",
          width: "5.2%",
          height: "50.2%",
        },
        {
          nome: "lavanderia",
          top: "49.4%",
          left: "0.9%",
          width: "12%",
          height: "16.8%",
        },
        {
          nome: "corredor",
          top: "57%",
          left: "13.6%",
          width: "13.4%",
          height: "9.2%",
        },
        {
          nome: "corredor-recorte",
          top: "54.2%",
          left: "21.3%",
          width: "5.7%",
          height: "2.8%",
        },
        {
          nome: "banheiro_1",
          top: "51%",
          left: "27.7%",
          width: "9.3%",
          height: "15.2%",
        },
        {
          nome: "banheiro_1-recorte",
          top: "56%",
          left: "36.95%",
          width: "6.2%",
          height: "10.2%",
        },
        {
          nome: "quarto_1",
          top: "67.5%",
          left: "0.9%",
          width: "18.2%",
          height: "31%",
        },
        {
          nome: "quarto_2",
          top: "67.5%",
          left: "19.8%",
          width: "17.1%",
          height: "31%",
        },
        {
          nome: "area_livre",
          top: "67.5%",
          left: "37.6%",
          width: "11.4%",
          height: "31%",
        },
        {
          nome: "banheiro_2",
          top: "67.5%",
          left: "49.6%",
          width: "8.2%",
          height: "31%",
        },
        {
          nome: "quarto_3",
          top: "66.2%",
          left: "58.6%",
          width: "18.3%",
          height: "32.3%",
        },
        {
          nome: "quarto_3-recorte",
          top: "56%",
          left: "49.7%",
          width: "27.2%",
          height: "10.2%",
        },
      ],
    },
    
    {
      nome: "Nível 3",
      subnome: "100m² - 120m²",
      dificuldadeRaio: 390,
      dificuldadeTempo: 25,
      imagem: "../img/nivel-3/mapa-4.svg",
      roteadores: 2,
      tamanho: "800px",
      abrangencia: {
        width: "400px",
        height: "400px",
      },
      areas: [
        {
          nome: "banheiro_1",
          top: "1.5%",
          left: "1%",
          width: "20.7%",
          height: "20%",
        },
        {
          nome: "closet",
          top: "23%",
          left: "1%",
          width: "20.7%",
          height: "20%",
        },
        {
          nome: "dormitorio_1",
          top: "44.5%",
          left: "1%",
          width: "20.7%",
          height: "54%",
        },
        {
          nome: "quarto_1",
          top: "1.5%",
          left: "22.5%",
          width: "22%",
          height: "41.2%",
        },
        {
          nome: "corredor",
          top: "44.5%",
          left: "22.5%",
          width: "23%",
          height: "10.8%",
        },
        {
          nome: "quarto_2",
          top: "57%",
          left: "22.5%",
          width: "20.8%",
          height: "41.2%",
        },
        {
          nome: "sala",
          top: "1.5%",
          left: "45.5%",
          width: "53.3%",
          height: "53.9%",
        },
        {
          nome: "banheiro_2",
          top: "57%",
          left: "44.3%",
          width: "11%",
          height: "41.2%",
        },
        {
          nome: "despensa",
          top: "57%",
          left: "56.2%",
          width: "12.7%",
          height: "14.8%",
        },
        {
          nome: "lavanderia",
          top: "73.2%",
          left: "56.2%",
          width: "12.7%",
          height: "25%",
        },
        {
          nome: "cozinha",
          top: "55.4%",
          left: "69.8%",
          width: "22.1%",
          height: "43%",
        },
      ],
    },  
  ],
  "nivel-4": [
    
    {
      nome: "Nível 4",
      subnome: "120m² - 170m²",
      dificuldadeRaio: 350,
      dificuldadeTempo: 30,
      imagem: "../img/nivel-4/mapa-1.svg",
      roteadores: 3,
      tamanho: "800px",
      abrangencia: {
        width: "330px",
        height: "330px",
      },
      areas: [
        {
          nome: "festeiro",
          top: "1.4%",
          left: "0.85%",
          width: "26.95%",
          height: "38.1%",
        },
        {
          nome: "cozinha",
          top: "1.3%",
          left: "28.65%",
          width: "36%",
          height: "38.19%",
        },
        {
          nome: "sala",
          top: "1.3%",
          left: "64.65%",
          width: "19%",
          height: "38.1%",
        },
        {
          nome: "sala-recorte",
          top: "26.7%",
          left: "83.65%",
          width: "11.1%",
          height: "12.8%",
        },
        {
          nome: "escritorio",
          top: "1.3%",
          left: "84.4%",
          width: "10.3%",
          height: "24%",
        },
        {
          nome: "lavanderia",
          top: "40.9%",
          left: "0.85%",
          width: "8.37%",
          height: "43.2%",
        },
        {
          nome: "quarto_1-recorte",
          top: "40.9%",
          left: "10%",
          width: "8.2%",
          height: "14%",
        },
        {
          nome: "quarto_1",
          top: "40.9%",
          left: "18.2%",
          width: "16%",
          height: "43.2%",
        },
        {
          nome: "quarto_1-recorte2",
          top: "40.9%",
          left: "34.2%",
          width: "4.35%",
          height: "9%",
        },
        {
          nome: "banheiro_1",
          top: "56.2%",
          left: "10%",
          width: "7.4%",
          height: "27.9%",
        },
        {
          nome: "corredor",
          top: "40.9%",
          left: "39.4%",
          width: "18.7%",
          height: "9%",
        },
        {
          nome: "quarto_2",
          top: "51.1%",
          left: "35%",
          width: "15.1%",
          height: "33%",
        },
        {
          nome: "banheiro_2",
          top: "51.1%",
          left: "50.85%",
          width: "7.3%",
          height: "33%",
        },
        {
          nome: "quarto_3",
          top: "40.9%",
          left: "58.9%",
          width: "15.3%",
          height: "43.2%",
        },
        {
          nome: "garagem",
          top: "40.9%",
          left: "75%",
          width: "25%",
          height: "57.8%",
        },
      ],
    },
    
    {
      nome: "Nível 4",
      subnome: "120m² - 170m²",
      dificuldadeRaio: 330,
      dificuldadeTempo: 30,
      imagem: "../img/nivel-4/mapa-2.svg",
      roteadores: 3,
      tamanho: "870px",
      abrangencia: {
        width: "340px",
        height: "340px",
      },
      areas: [
        {
          nome: "lavanderia",
          top: "14.1%",
          left: "10%",
          width: "7.7%",
          height: "38.5%",
        },
        {
          nome: "banheiro_1",
          top: "14.1%",
          left: "18.3%",
          width: "6.8%",
          height: "24.8%",
        },
        {
          nome: "quarto_1",
          top: "14.1%",
          left: "25.8%",
          width: "14.6%",
          height: "38.4%",
        },
        {
          nome: "quarto_1-recorte_1",
          top: "40%",
          left: "18.3%",
          width: "7.5%",
          height: "12.5%",
        },
        {
          nome: "quarto_1-recorte_2",
          top: "44.3%",
          left: "40.4%",
          width: "4%",
          height: "8.2%",
        },
        {
          nome: "corredor",
          top: "44.3%",
          left: "45%",
          width: "17%",
          height: "8.2%",
        },
        {
          nome: "quarto_2",
          top: "14.1%",
          left: "41.1%",
          width: "13.7%",
          height: "29.2%",
        },
        {
          nome: "banheiro_2",
          top: "14.1%",
          left: "55.4%",
          width: "6.7%",
          height: "29.2%",
        },
        {
          nome: "quarto_3",
          top: "14.1%",
          left: "62.7%",
          width: "14%",
          height: "38.4%",
        },
        {
          nome: "garagem",
          top: "1.2%",
          left: "77.3%",
          width: "22.6%",
          height: "51.3%",
        },
        {
          nome: "area_gormet",
          top: "53.6%",
          left: "25.3%",
          width: "19.5%",
          height: "34%",
        },
        {
          nome: "cozinha",
          top: "53.6%",
          left: "45.5%",
          width: "23%",
          height: "34%",
        },
        {
          nome: "sala",
          top: "53.6%",
          left: "68.5%",
          width: "26.8%",
          height: "34%",
        },
      ],
    },

    {
      nome: "Nível 4",
      subnome: "120m² - 170m²",
      dificuldadeRaio: 360,
      dificuldadeTempo: 30,
      imagem: "../img/nivel-4/mapa-3.svg",
      roteadores: 3,
      tamanho: "970px",
      abrangencia: {
        width: "360px",
        height: "360px",
      },
      areas: [
        {
          nome: "closet",
          top: "1.1%",
          left: "18.3%",
          width: "8.3%",
          height: "32.5%",
        },
        {
          nome: "banheiro_1",
          top: "1.1%",
          left: "27.1%",
          width: "5.5%",
          height: "25%",
        },
        {
          nome: "quarto_1",
          top: "1.1%",
          left: "33.2%",
          width: "17.5%",
          height: "25%",
        },
        {
          nome: "sala",
          top: "1.1%",
          left: "51.3%",
          width: "26.4%",
          height: "34%",
        },
        {
          nome: "ducha",
          top: "34.9%",
          left: "18.3%",
          width: "8.3%",
          height: "24.5%",
        },
        {
          nome: "festeiro",
          top: "60.8%",
          left: "0.6%",
          width: "17.1%",
          height: "31%",
        },
        {
          nome: "quarto_2",
          top: "27.3%",
          left: "27.1%",
          width: "13.7%",
          height: "32.2%",
        },
        {
          nome: "quarto_2-recorte",
          top: "27.3%",
          left: "40.8%",
          width: "9.9%",
          height: "7.8%",
        },
        {
          nome: "quarto_3",
          top: "36.3%",
          left: "41.4%",
          width: "13.9%",
          height: "23.3%",
        },
        {
          nome: "lavanderia",
          top: "36.3%",
          left: "55.8%",
          width: "7.3%",
          height: "23.3%",
        },
        {
          nome: "cozinha",
          top: "35%",
          left: "63.7%",
          width: "14%",
          height: "17%",
        },
        {
          nome: "cozinha-recorte",
          top: "52%",
          left: "63.7%",
          width: "10%",
          height: "7.5%",
        },
        {
          nome: "cozinha-angulo",
          top: "51.9%",
          left: "73.67%",
          width: "4.1%",
          height: "7.7%",
          clipPath: "polygon(100% 0%, 0% 100%, 0% 0%)",
        },
        {
          nome: "sala_estar",
          top: "1.1%",
          left: "78.3%",
          width: "21%",
          height: "30%",
        },
        {
          nome: "garagem",
          top: "32%",
          left: "78.3%",
          width: "19.7%",
          height: "49.6%",
        },
      ],
    },

    

    {
      nome: "Nível 4",
      subnome: "120m² - 170m²",
      dificuldadeRaio: 310,
      dificuldadeTempo: 30,
      imagem: "../img/nivel-4/mapa-4.svg",
      roteadores: 4,
      tamanho: "1100px",
      abrangencia: {
        width: "320px",
        height: "320px",
      },
      areas: [
        {
          nome: "festeiro",
          top: "16.6%",
          left: "0.5%",
          width: "13.7%",
          height: "38.2%",
        },
        {
          nome: "banheiro_1",
          top: "16.6%",
          left: "22.4%",
          width: "5.1%",
          height: "27.9%",
        },
        {
          nome: "quarto_1",
          top: "16.6%",
          left: "27.9%",
          width: "11.4%",
          height: "29%",
        },
        {
          nome: "quarto_1-recorte",
          top: "45.6%",
          left: "22.4%",
          width: "16.9%",
          height: "20.8%",
        },
        {
          nome: "quarto_2",
          top: "16.6%",
          left: "39.8%",
          width: "10.7%",
          height: "37.8%",
        },
        {
          nome: "quarto_3",
          top: "16.6%",
          left: "50.9%",
          width: "10.7%",
          height: "37.8%",
        },
        {
          nome: "banheiro_2",
          top: "16.6%",
          left: "62.1%",
          width: "5.1%",
          height: "27.9%",
        },
        {
          nome: "corredor-recorte",
          top: "45.5%",
          left: "62.1%",
          width: "5.1%",
          height: "20.5%",
        },
        {
          nome: "corredor",
          top: "55.6%",
          left: "39.8%",
          width: "22.3%",
          height: "10.5%",
        },
        {
          nome: "sala",
          top: "16.6%",
          left: "67.7%",
          width: "14.3%",
          height: "49.5%",
        },
        {
          nome: "garagem",
          top: "1.5%",
          left: "82.4%",
          width: "17.6%",
          height: "64.6%",
        },
        {
          nome: "escritorio",
          top: "67.5%",
          left: "82.4%",
          width: "15.4%",
          height: "31%",
        },
        {
          nome: "sala_jantar",
          top: "67.5%",
          left: "67.7%",
          width: "14.3%",
          height: "31%",
        },
        {
          nome: "cozinha",
          top: "67.5%",
          left: "52%",
          width: "15.2%",
          height: "31%",
        },
        {
          nome: "area_luz",
          top: "67.5%",
          left: "44.3%",
          width: "7.3%",
          height: "31%",
        },
        {
          nome: "lavanderia",
          top: "67.5%",
          left: "33.1%",
          width: "10.7%",
          height: "31%",
        },
      ],
    },
    
  ],
  "nivel-5": [
    
     {
      nome: "Nível 5",
      subnome: "170m²+",
      dificuldadeRaio: 290,
      dificuldadeTempo: 30,
      imagem: "../img/nivel-5/mapa-1.svg",
      roteadores: 6,
      tamanho: "1100px",
      abrangencia: {
        width: "290px",
        height: "290px",
      },
      areas: [
        {
          nome: "area_luz",
          top: "1%",
          left: "0.4%",
          width: "4.4%",
          height: "19%",
        },
        {
          nome: "banheiro_1",
          top: "20.7%",
          left: "0.4%",
          width: "4.4%",
          height: "16.4%",
        },
        {
          nome: "banheiro_2",
          top: "1%",
          left: "5.2%",
          width: "3.8%",
          height: "19%",
        },
        {
          nome: "quarto_1",
          top: "1%",
          left: "9.3%",
          width: "9.3%",
          height: "19.8%",
        },
        {
          nome: "quarto_1-recorte",
          top: "20.8%",
          left: "5.2%",
          width: "13.4%",
          height: "7.7%",
        },
        {
          nome: "quarto_1-recorte_2",
          top: "28.5%",
          left: "5.2%",
          width: "7.8%",
          height: "8.5%",
        },
        {
          nome: "quarto_2",
          top: "1%",
          left: "19%",
          width: "9.2%",
          height: "27.5%",
        },
        {
          nome: "banheiro_3",
          top: "1%",
          left: "28.6%",
          width: "4.9%",
          height: "13.3%",
        },
        {
          nome: "banheiro_4",
          top: "1%",
          left: "33.8%",
          width: "4.9%",
          height: "13.3%",
        },
        {
          nome: "closet_1",
          top: "15%",
          left: "28.6%",
          width: "4.9%",
          height: "13.4%",
        },
        {
          nome: "closet_1",
          top: "15%",
          left: "33.8%",
          width: "4.9%",
          height: "13.4%",
        },
        {
          nome: "quarto_3",
          top: "1%",
          left: "39%",
          width: "9.2%",
          height: "27.5%",
        },
        {
          nome: "sala_tv",
          top: "1%",
          left: "48.5%",
          width: "11.7%",
          height: "27.5%",
        },
        {
          nome: "sala_estar",
          top: "17.4%",
          left: "60.5%",
          width: "11.5%",
          height: "11%",
        },
        {
          nome: "sala_estar-recorte",
          top: "1%",
          left: "60.5%",
          width: "15.6%",
          height: "16.5%",
        },
        {
          nome: "sala_jantar",
          top: "37%",
          left: "52.5%",
          width: "19.5%",
          height: "22.4%",
        },
        {
          nome: "sala_jantar-recorte",
          top: "29.3%",
          left: "48.5%",
          width: "23.5%",
          height: "7.8%",
        },
        {
          nome: "cozinha",
          top: "59.4%",
          left: "52.5%",
          width: "19.5%",
          height: "9.5%",
        },
        {
          nome: "cozinha-recorte_2",
          top: "68.9%",
          left: "52.5%",
          width: "18.5%",
          height: "9.8%",
        },
        {
          nome: "cozinha-recorte_1",
          top: "78.7%",
          left: "52.5%",
          width: "14.2%",
          height: "8.8%",
        },
        {
          nome: "lavabo",
          top: "69.8%",
          left: "71.4%",
          width: "4.5%",
          height: "8.9%",
        },
        {
          nome: "deposito_1",
          top: "69.8%",
          left: "76.2%",
          width: "6.2%",
          height: "22.9%",
        },
        {
          nome: "escritorio",
          top: "79.6%",
          left: "67%",
          width: "9%",
          height: "19.5%",
        },
        {
          nome: "despensa",
          top: "88.2%",
          left: "62.2%",
          width: "4.5%",
          height: "10.7%",
        },
        {
          nome: "lavanderia",
          top: "88.2%",
          left: "52.6%",
          width: "9.3%",
          height: "10.7%",
        },
        {
          nome: "deposito_2",
          top: "88.2%",
          left: "48.3%",
          width: "4%",
          height: "10.7%",
        },
        {
          nome: "banheiro_5",
          top: "88.2%",
          left: "41.7%",
          width: "6.3%",
          height: "10.7%",
        },
        {
          nome: "area_gourmet",
          top: "38%",
          left: "36.2%",
          width: "16%",
          height: "21.6%",
        },
        {
          nome: "area_gourmet-recorte",
          top: "59.6%",
          left: "41.5%",
          width: "10.7%",
          height: "28%",
        },
        {
          nome: "academia",
          top: "37.9%",
          left: "23.6%",
          width: "12.2%",
          height: "21.1%",
        },
        {
          nome: "banheiro_6",
          top: "37.9%",
          left: "16.4%",
          width: "6.9%",
          height: "9.8%",
        },
        {
          nome: "corredor",
          top: "29.3%",
          left: "13.44%",
          width: "18%",
          height: "7.8%",
        },
        {
          nome: "corredor-recorte",
          top: "29.3%",
          left: "31.45%",
          width: "16.8%",
          height: "7.8%",
        },
        {
          nome: "ligamento",
          top: "37.9%",
          left: "9.7%",
          width: "6.4%",
          height: "9.8%",
        },
        {
          nome: "ligamento-recorte",
          top: "47.7%",
          left: "9.7%",
          width: "2.6%",
          height: "13.5%",
        },
        {
          nome: "closet",
          top: "37.9%",
          left: "0.4%",
          width: "8.9%",
          height: "23.4%",
        },
        {
          nome: "suite",
          top: "62.1%",
          left: "0.4%",
          width: "12%",
          height: "31%",
        },
      ],
    }, 

       {
      nome: "Nível 5",
      subnome: "170m²+",
      dificuldadeRaio: 270,
      dificuldadeTempo: 30,
      imagem: "../img/nivel-5/mapa-2.svg",
      roteadores: 5,
      tamanho: "800px",
      abrangencia: {
        width: "270px",
        height: "270px",
      },
      areas: [
        {
          nome: "festeiro",
          top: "1%",
          left: "4.7%",
          width: "14.4%",
          height: "19%",
        },
        {
          nome: "corredor",
          top: "1%",
          left: "34%",
          width: "61.3%",
          height: "9.5%",
        },
        {
          nome: "area_gormet",
          top: "11.6%",
          left: "34%",
          width: "10.2%",
          height: "67%",
        },
        {
          nome: "area_gormet-recorte",
          top: "11.6%",
          left: "44.2%",
          width: "7.2%",
          height: "48.8%",
        },
        {
          nome: "cozinha",
          top: "11.6%",
          left: "51.8%",
          width: "22%",
          height: "42%",
        },
        {
          nome: "cozinha-recorte",
          top: "53.6%",
          left: "51.8%",
          width: "19.5%",
          height: "6.7%",
        },
        {
          nome: "sala",
          top: "11.6%",
          left: "74.4%",
          width: "20.5%",
          height: "42%",
        },
        {
          nome: "sala-recorte",
          top: "11.6%",
          left: "94.9%",
          width: "4.5%",
          height: "29.2%",
        },
        {
          nome: "garagem",
          top: "54.5%",
          left: "78.75%",
          width: "21%",
          height: "44.4%",
        },
        {
          nome: "ligamento",
          top: "54.5%",
          left: "71.8%",
          width: "6.4%",
          height: "10%",
        },
        {
          nome: "quarto_1",
          top: "65.3%",
          left: "65%",
          width: "13.2%",
          height: "23%",
        },
        {
          nome: "quarto_1-recorte",
          top: "61.3%",
          left: "65%",
          width: "6.3%",
          height: "4%",
        },
        {
          nome: "closet",
          top: "61.3%",
          left: "51.8%",
          width: "12.5%",
          height: "13.6%",
        },
        {
          nome: "deposito",
          top: "61.3%",
          left: "44.8%",
          width: "6.5%",
          height: "11.3%",
        },
        {
          nome: "lavanderia",
          top: "73.6%",
          left: "44.8%",
          width: "6.5%",
          height: "14.8%",
        },
        {
          nome: "banheiro",
          top: "75.8%",
          left: "51.8%",
          width: "12.6%",
          height: "12.5%",
        },
        {
          nome: "banheiro_2",
          top: "79.5%",
          left: "34%",
          width: "10.3%",
          height: "9%",
        },
        {
          nome: "corredor_2",
          top: "89.5%",
          left: "34%",
          width: "44.2%",
          height: "9.4%",
        },
      ],
    }, 
    
    
     {
      nome: "Nível 5",
      subnome: "170m²+",
      dificuldadeRaio: 235,
      dificuldadeTempo: 30,
      imagem: "../img/nivel-5/mapa-3.svg",
      roteadores: 6,
      tamanho: "700px",
      abrangencia: {
        width: "250px",
        height: "250px",
      },
      areas: [
        {
          nome: "banheiro_1",
          top: "0.5%",
          left: "0.4%",
          width: "9%",
          height: "6.3%",
        },
        {
          nome: "banheiro_2",
          top: "0.5%",
          left: "13.8%",
          width: "9%",
          height: "6.3%",
        },
        {
          nome: "despensa_1",
          top: "0.5%",
          left: "23.4%",
          width: "9%",
          height: "6.3%",
        },
        {
          nome: "academia",
          top: "7.5%",
          left: "0.4%",
          width: "9.1%",
          height: "34.4%",
        },
        {
          nome: "academia-recorte",
          top: "11.5%",
          left: "9.5%",
          width: "3.8%",
          height: "30.4%",
        },
        {
          nome: "area_gourmet",
          top: "7.5%",
          left: "13.8%",
          width: "21.5%",
          height: "13%",
        },
        {
          nome: "area_gourmet_descanso",
          top: "20.5%",
          left: "13.8%",
          width: "21.5%",
          height: "21.4%",
        },
        {
          nome: "area_gourmet-recorte1",
          top: "0%",
          left: "10%",
          width: "3.4%",
          height: "7.3%",
        },
        {
          nome: "area_gourmet-recorte2",
          top: "7.3%",
          left: "10%",
          width: "3.8%",
          height: "3.8%",
        },
        {
          nome: "area_gourmet-recorte3",
          top: "0%",
          left: "32.7%",
          width: "2.6%",
          height: "7.5%",
        },
        {
          nome: "lavanderia_1",
          top: "0.4%",
          left: "35.8%",
          width: "8.8%",
          height: "9.3%",
        },
        {
          nome: "despensa_2",
          top: "10%",
          left: "35.8%",
          width: "8.8%",
          height: "5.6%",
        },
        {
          nome: "banheiro_3",
          top: "0.4%",
          left: "51.8%",
          width: "9.3%",
          height: "5.4%",
        },
        {
          nome: "dormitorio_servico",
          top: "6.3%",
          left: "51.8%",
          width: "9.3%",
          height: "9.2%",
        },
        {
          nome: "cozinha-recorte",
          top: "10%",
          left: "45%",
          width: "6.4%",
          height: "6%",
        },
        {
          nome: "cozinha",
          top: "16%",
          left: "42.8%",
          width: "18.3%",
          height: "14%",
        },
        {
          nome: "cozinha_corredor",
          top: "30%",
          left: "42.8%",
          width: "18.3%",
          height: "14.4%",
        },
        {
          nome: "corredor",
          top: "16%",
          left: "35.8%",
          width: "6.6%",
          height: "26.6%",
        },
        {
          nome: "banheiro_4",
          top: "35.8%",
          left: "61.5%",
          width: "4.3%",
          height: "8.6%",
        },
        {
          nome: "despensa_3",
          top: "35.8%",
          left: "66.3%",
          width: "4.1%",
          height: "8.6%",
        },
        {
          nome: "sala_jantar",
          top: "45%",
          left: "42.8%",
          width: "21.7%",
          height: "14.7%",
        },
        {
          nome: "sala_estar",
          top: "45%",
          left: "64.5%",
          width: "25.3%",
          height: "14.6%",
        },
        {
          nome: "sala_maquina",
          top: "42%",
          left: "78.9%",
          width: "11%",
          height: "2.4%",
        },
        {
          nome: "sala_jantar2",
          top: "59.7%",
          left: "46.5%",
          width: "18%",
          height: "18.4%",
        },
        {
          nome: "sala_jantar2-recorte2",
          top: "59.7%",
          left: "42.8%",
          width: "3.7%",
          height: "2.7%",
        },
        {
          nome: "sala_jantar2-recorte",
          top: "78.1%",
          left: "54.5%",
          width: "7.4%",
          height: "5.3%",
        },
        {
          nome: "sala_cinema",
          top: "60.2%",
          left: "64.8%",
          width: "14.6%",
          height: "18%",
        },
        {
          nome: "escritorio",
          top: "60.2%",
          left: "79.9%",
          width: "9.8%",
          height: "18%",
        },
        {
          nome: "deposito",
          top: "78.7%",
          left: "46.7%",
          width: "7.4%",
          height: "4.6%",
        },
        {
          nome: "banheiro_5",
          top: "84%",
          left: "46.7%",
          width: "7.4%",
          height: "7.9%",
        },
        {
          nome: "closet",
          top: "84%",
          left: "54.6%",
          width: "7.2%",
          height: "7.9%",
        },
        {
          nome: "dormitorio",
          top: "78.6%",
          left: "62.3%",
          width: "10.5%",
          height: "13.3%",
        },
        {
          nome: "despensafora",
          top: "78.7%",
          left: "73.1%",
          width: "6.3%",
          height: "13.3%",
        },
        {
          nome: "festeiro",
          top: "74%",
          left: "0.4%",
          width: "7.4%",
          height: "17%",
        },
        {
          nome: "festeiro-recorte",
          top: "91%",
          left: "0.4%",
          width: "13%",
          height: "8.5%",
        },
      ],
    },  
  ],
};

export { mapas };
