const mapas = [
  {
    nome: "Nível 1",
    subnome: "80m² - 100m²",
    dificuldadeRaio: 447,
    dificuldadeTempo: 25,
    imagem: "../img/nivel-1/mapa-1.svg",
    areas: [
      {
        nome: "sala",
        top: "2.2%",
        left: "61.4%",
        width: "32.85%",
        height: "62%",
      },
      {
        nome: "sala-angulo",
        top: "22%",
        left: "94.21%",
        width: "4.7%",
        height: "10%",
        clipPath: "polygon(0% 0%, 0% 100%, 100% 100%)",
      },
      {
        nome: "sala-recorte",
        top: "32%",
        left: "94.21%",
        width: "4.53%",
        height: "32.2%",
      },
      {
        nome: "corredor",
        top: "49.3%",
        left: "20.7%",
        width: "40.7%",
        height: "14.9%",
      },
      {
        nome: "cozinha",
        top: "66.1%",
        left: "61.4%",
        width: "37.35%",
        height: "31.8%",
      },
      {
        nome: "quarto_1",
        top: "2.2%",
        left: "1.1%",
        width: "27.2%",
        height: "44.9%",
      },
      {
        nome: "quarto_2",
        top: "2.2%",
        left: "40%",
        width: "20.4%",
        height: "44.9%",
      },
      {
        nome: "quarto_3",
        top: "49.3%",
        left: "1.1%",
        width: "18.6%",
        height: "48.6%",
      },
      {
        nome: "quarto_3-recorte",
        top: "66.1%",
        left: "19.7%",
        width: "24.2%",
        height: "31.8%",
      },
      {
        nome: "banheiro_1",
        top: "2.2%",
        left: "29.3%",
        width: "9.7%",
        height: "44.7%",
      },
      {
        nome: "banheiro_2",
        top: "66.1%",
        left: "44.9%",
        width: "15.5%",
        height: "31.8%",
      },
    ],
    roteadores: 2,
  },
  {
    nome: "Nível 2",
    subnome: "100m² - 120m²",
    dificuldadeRaio: 440,
    dificuldadeTempo: 25,
    imagem: "../img/nivel-2/mapa-1.svg",
    areas: [
      {
        nome: "sala",
        top: "55.8%",
        left: "61.3%",
        width: "30.3%",
        height: "42.4%",
      },
      {
        nome: "sala-recorte",
        top: "67.2%",
        left: "91.6%",
        width: "7.4%",
        height: "31%",
      },
      {
        nome: "corredor",
        top: "42.3%",
        left: "14.8%",
        width: "46.1%",
        height: "11.9%",
      },
      {
        nome: "cozinha_1",
        top: "55.8%",
        left: "37.3%",
        width: "24.07%",
        height: "42.4%",
      },
      {
        nome: "cozinha_1-2",
        top: "55.8%",
        left: "14.8%",
        width: "22.5%",
        height: "42.4%",
      },
      {
        nome: "quarto_1",
        top: "1.7%",
        left: "0.87%",
        width: "20.1%",
        height: "31.2%",
      },
      {
        nome: "quarto_1-recorte",
        top: "32.8%",
        left: "14.8%",
        width: "6.2%",
        height: "7.6%",
      },
      {
        nome: "quarto_2",
        top: "1.7%",
        left: "30.7%",
        width: "17.1%",
        height: "38.8%",
      },
      {
        nome: "quarto_3",
        top: "1.7%",
        left: "48.7%",
        width: "12.3%",
        height: "38.8%",
      },
      {
        nome: "quarto_4",
        top: "1.7%",
        left: "61.8%",
        width: "17.2%",
        height: "52.3%",
      },
      {
        nome: "quarto_4-recorte",
        top: "35.4%",
        left: "79%",
        width: "12.7%",
        height: "18.6%",
      },
      {
        nome: "banheiro_1",
        top: "1.7%",
        left: "21.8%",
        width: "8%",
        height: "38.8%",
      },
      {
        nome: "banheiro_2",
        top: "1.7%",
        left: "79.8%",
        width: "11.9%",
        height: "32%",
      },
      {
        nome: "lavanderia",
        top: "34.8%",
        left: "0.87%",
        width: "13.1%",
        height: "19.2%",
      },
    ],
    roteadores: 2,
  },
  {
    nome: "Nível 3",
    subnome: "120m² - 170m²",
    dificuldadeRaio: 440,
    dificuldadeTempo: 30,
    imagem: "../img/nivel-3/mapa-1.svg",
    areas: [
      {
        nome: "festeiro",
        top: "1.4%",
        left: "0.85%",
        width: "26.95%",
        height: "38.1%",
      },
      {
        nome: "cozinha",
        top: "1.3%",
        left: "28.65%",
        width: "36%",
        height: "38.19%",
      },
      {
        nome: "sala",
        top: "1.3%",
        left: "64.65%",
        width: "19%",
        height: "38.1%",
      },
      {
        nome: "sala-recorte",
        top: "26.7%",
        left: "83.65%",
        width: "11.1%",
        height: "12.8%",
      },
      {
        nome: "escritorio",
        top: "1.3%",
        left: "84.5%",
        width: "10.3%",
        height: "24%",
      },
      {
        nome: "lavanderia",
        top: "40.9%",
        left: "0.85%",
        width: "8.37%",
        height: "43.2%",
      },
      {
        nome: "quarto_1-recorte",
        top: "40.9%",
        left: "10%",
        width: "8.2%",
        height: "14%",
      },
      {
        nome: "quarto_1",
        top: "40.9%",
        left: "18.2%",
        width: "16%",
        height: "43.2%",
      },
      {
        nome: "quarto_1-recorte2",
        top: "40.9%",
        left: "34.2%",
        width: "4.35%",
        height: "9%",
      },
      {
        nome: "banheiro_1",
        top: "56.2%",
        left: "10%",
        width: "7.4%",
        height: "27.9%",
      },
      {
        nome: "corredor",
        top: "40.9%",
        left: "39.4%",
        width: "18.7%",
        height: "9%",
      },
      {
        nome: "quarto_2",
        top: "51.1%",
        left: "35%",
        width: "15.1%",
        height: "33%",
      },
      {
        nome: "banheiro_2",
        top: "51.1%",
        left: "50.85%",
        width: "7.3%",
        height: "33%",
      },
      {
        nome: "quarto_3",
        top: "40.9%",
        left: "58.9%",
        width: "15.3%",
        height: "43.2%",
      },
      {
        nome: "garagem",
        top: "40.9%",
        left: "75%",
        width: "25%",
        height: "57.8%",
      },
    ],
    roteadores: 3,
  },
];
